version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_agri
    environment:
      POSTGRES_USER: agri
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  postgrest:
    image: postgrest/postgrest
    container_name: postgrest_agri
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./postgrest.conf:/etc/postgrest.conf
    networks:
      - backend
    command: postgrest /etc/postgrest.conf

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"  # Change the password if needed
    ports:
      - "3001:3000"  # You can access Grafana via localhost:3001
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - postgres
    networks:
      - backend

volumes:
  pgdata:
  grafana_data:

networks:
  backend:
