version: '3.7'
services:
    api-postgrest:
        image: postgrest/postgrest
        ports:
            - "3000:3000"
        depends_on:
            - database-postgres
        environment:
            - PGRST_DB_URI=postgres://postgres:postgres@database-postgres:5432/${DATABASE_NAME}
            - PGRST_DB_SCHEMA=${PGRST_DB_SCHEMA} #public
            - PGRST_DB_ANON_ROLE=${PGRST_DB_ANON_ROLE} #web_anon

    database-postgres:
        image: postgres:10.5
        restart: always
        environment: 
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=${DATABASE_NAME}

        ports:
          - '5438:5432'
        volumes:
          # - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          # - pgdata:/var/lib/postgresql/data
          - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
          - ./sql/create_roles.sql:/docker-entrypoint-initdb.d/create_roles.sql


volumes:

    pgdata: